"""One-off helper: generates a fresh VAPID key pair for Web Push (RFC 8292).

Unlike every other credential in this project, VAPID keys have no external account
behind them — they're just a self-generated EC keypair proving to the browser's push
service that pushes come from the same server every time. Nothing to sign up for,
nothing that can be revoked by a third party, no card, no blocker.

Usage:
    python scripts/generate_vapid_keys.py            # prints both keys
    python scripts/generate_vapid_keys.py --write-env # also appends to .env directly

The public key is safe to expose to any browser (it's sent to PushManager.subscribe()
as the applicationServerKey) — the private key is not; treat it like any other secret
in .env (gitignored) or a CI/host secret, never commit it.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric import ec  # noqa: E402
from py_vapid.utils import b64urlencode, num_to_bytes  # noqa: E402

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def generate() -> tuple[str, str]:
    private_key = ec.generate_private_key(ec.SECP256R1())
    private_raw = num_to_bytes(private_key.private_numbers().private_value, 32)
    public_raw = private_key.public_key().public_bytes(
        serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
    )
    return b64urlencode(private_raw), b64urlencode(public_raw)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-env", action="store_true", help="append the keys directly to .env")
    args = parser.parse_args()

    private_b64, public_b64 = generate()

    if args.write_env:
        existing = ENV_PATH.read_text(encoding="utf-8") if ENV_PATH.exists() else ""
        if "VAPID_PRIVATE_KEY" in existing:
            print(".env already has VAPID_PRIVATE_KEY set — not overwriting. Remove it first if you want new keys.")
            return
        with ENV_PATH.open("a", encoding="utf-8") as f:
            f.write("\n# --- Web Push VAPID keys (generated by scripts/generate_vapid_keys.py) ---\n")
            f.write(f"VAPID_PUBLIC_KEY={public_b64}\n")
            f.write(f"VAPID_PRIVATE_KEY={private_b64}\n")
            f.write("VAPID_CLAIMS_EMAIL=mailto:example@example.com\n")
        print(f"Wrote VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_CLAIMS_EMAIL to {ENV_PATH}")
        print("Set a real contact address for VAPID_CLAIMS_EMAIL before deploying (push services use it to")
        print("contact you if your server is misbehaving) — the placeholder is fine for local dev.")
    else:
        print(f"VAPID_PUBLIC_KEY={public_b64}")
        print(f"VAPID_PRIVATE_KEY={private_b64}")
        print("VAPID_CLAIMS_EMAIL=mailto:example@example.com")


if __name__ == "__main__":
    main()
